#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00

set -x
# set -e

input=$(jq -r .t1 config.json)
tta=$(jq -r .tta config.json)
mode=$(jq -r .mode config.json)

case "$tta" in
 true) tta=1 ;;
 *) tta=0 ;;
esac

#pick cpu v.s. nvidia gpu
device=cpu
nvopts=""

# Check if nvidia is installed
if hash nvidia-smi; then
    # Check if everything is correctly loaded
    nvidia-smi &> /dev/null
    if [ $? == 0 ]; then
        #TODO - pick an appropriate device instead of 0
        device=0 
        nvopts="--nv"
    fi
fi

time singularity run $nvopts -e docker://anibalsolon/hd-bet:v0.0.1 hd-bet \
    -i $input \
    -o masked.nii.gz \
    -device $device \
    -mode $mode \
    -tta $tta

mkdir -p mask
cp masked_mask.nii.gz mask/t1.nii.gz

mkdir -p output
cp masked.nii.gz output/t1.nii.gz
