#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=02:00:00

set -x

export input=$(jq -r .input config.json)

singularity exec -e docker://anibalsolon/hd-bet:0.0.1 hd-bet -i $input -o masked.nii.gz -device cpu -mode fast -tta 0

mkdir -p mask
cp masked_mask.nii.gz mask/mask.nii.gz


hd-bet
